Graph traits redux
facebookresearch/dachshund pull request #21
Opened 2020-09-29 03:00 UTC by bogdanstate

`SimpleUndirectedGraph` has been growing enormously, and a refactor seems in order. It feels logical to divide different problem areas around graph mining using trait composition. This has the additional benefit of allowing reuse of the same algorithms for multiple kinds of graphs.

An important part of this change required the introduction of new base traits for `Node` and `NodeEdge`, the introduction of a `NodeType` associate type to `GraphBase`, with `TypedGraph` constraining the implementation of `NodeType = Node`, to avoid an even more involved refactor.

The general pattern I would like to move towards is having new algorithms implemented in separate traits, that nonetheless attach to `SimpleUndirectedGraphs`. This will also help us draw a neat dependency graph (heh) between the various traits, where for instance we can see that `Coreness` demands `ConnectedComponents`.

2020-10-07 17:50 UTC, mlmenard requested changes
This is a big improvement!

2 things: Do you think it makes sense to have a separate algorithms folder (like use lib_dachshund::dachshund::algorithms::coreness)  instead of just having everything in dachshund?

Secondly, there are some leftovers from a failed merge. Can you fix those and update the PR so I can merge?

2020-10-07 17:50 UTC, mlmenard commented on src/dachshund/simple_undirected_graph.rs
> +<<<<<<< HEAD
Looks like there are some leftovers from a failed merge here.

2020-11-11 04:39 UTC, bogdanstate commented on src/dachshund/simple_undirected_graph.rs
> +<<<<<<< HEAD
Resolved!

2020-11-11 04:40 UTC, bogdanstate commented
@mlmenard, sorry for the long delay, replied to your comments and moved the code to an `algorithms` module.

2020-11-12 19:09 UTC, mlmenard approved these changes
Looks good to me now. Merging.

2020-11-12 19:10 UTC, merged